import{S as p,i as d}from"./assets/vendor-8c59ed88.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function a(r){if(r.ep)return;r.ep=!0;const n=s(r);fetch(r.href,n)}})();const y="https://pixabay.com/api/",m="42030436-f44bf17f2fc4b636ae2b8b7a9";function g(t,{page:e=1,perPage:s=20,lang:a="en"}={}){const r=new URLSearchParams({key:m,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:String(e),per_page:String(s),lang:a});return`${y}?${r.toString()}`}function h(t,e={}){const s=g(t,e);return fetch(s).then(a=>{if(!a.ok)throw new Error(`HTTP ${a.status}`);return a.json()})}const u=document.querySelector(".gallery"),c=document.querySelector(".loader-container"),b=new p(".gallery-item a",{captionsData:"alt",captionDelay:250});function S(t=[]){return t.map(({webformatURL:e,largeImageURL:s,tags:a,likes:r,views:n,comments:i,downloads:f})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${s}">
        <img class="gallery-image" src="${e}" alt="${$(a||"")}" loading="lazy" />
        <p class="gallery-descr">
          Likes: <span class="descr-span">${r}</span>
          &nbsp; Views: <span class="descr-span">${n}</span>
          &nbsp; Comments: <span class="descr-span">${i}</span>
          &nbsp; Downloads: <span class="descr-span">${f}</span>
        </p>
      </a>
    </li>
  `).join("")}function L(t=[],{replace:e=!0}={}){const s=S(t);e?u.innerHTML=s:u.insertAdjacentHTML("beforeend",s),b.refresh()}function P(){u.innerHTML=""}function q(){c.style.display="flex",c.innerHTML='<p style="margin:24px 0 0; color:#6b7280">Loading images, please wait…</p>'}function w(){c.style.display="none",c.innerHTML=""}function $(t){return String(t).replace(/[&<>"']/g,e=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[e])}const l={form:document.querySelector(".search-form"),gallery:document.querySelector(".gallery"),searchBtn:document.querySelector(".search-btn")};l.form.addEventListener("submit",x);function x(t){t.preventDefault();const e=l.form.elements.query.value.trim();if(!e){o("The search field can't be empty! Please, enter your request!");return}if(e.length>100){o("Search query must be 100 characters or less.");return}P(),q(),l.searchBtn.disabled=!0,h(e,{page:1,perPage:20,lang:"en"}).then(({hits:s})=>{if(!Array.isArray(s)||s.length===0){o("Sorry, there are no images matching your search query. Please, try again!");return}L(s,{replace:!0}),l.form.reset()}).catch(T).finally(()=>{w(),l.searchBtn.disabled=!1})}function T(t){var s,a,r;const e=(s=t==null?void 0:t.response)==null?void 0:s.status;if(e===429){const n=Number((r=(a=t.response)==null?void 0:a.headers)==null?void 0:r["x-ratelimit-reset"]);o(`API rate limit exceeded.${Number.isFinite(n)?` Try again in ~${Math.ceil(n)}s.`:""}`)}else o(e===401||e===403?"Invalid or missing Pixabay API key.":e===400?"Bad request. Please, check your query and try again.":"Something went wrong. Please, try again later.");console.error("Pixabay error:",t)}function o(t){d.show({class:"error-svg",position:"topRight",icon:"error-svg",message:t,maxWidth:"432",messageColor:"#fff",messageSize:"16px",backgroundColor:"#EF4040",close:!1,closeOnClick:!0})}
//# sourceMappingURL=commonHelpers.js.map
