import{S as f,i as d}from"./assets/vendor-8c59ed88.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const o of s.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&a(o)}).observe(document,{childList:!0,subtree:!0});function n(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=n(e);fetch(e.href,s)}})();const g="https://pixabay.com/api/",m="42030436-f44bf17f2fc4b636ae2b8b7a9";function y(t,{page:r=1,perPage:n=20,lang:a="en"}={}){const e=new URLSearchParams({key:m,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:String(r),per_page:String(n),lang:a});return`${g}?${e.toString()}`}function h(t,r={}){const n=y(t,r);return fetch(n).then(a=>{if(!a.ok)throw new Error(`HTTP ${a.status}`);return a.json()})}const u=document.querySelector(".gallery"),c=document.querySelector(".loader-container"),b=new f(".gallery-item a",{captionsData:"alt",captionDelay:250});function S(t=[]){return t.map(({webformatURL:r,largeImageURL:n,tags:a,likes:e,views:s,comments:o,downloads:p})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${n}">
        <img class="gallery-image" src="${r}" alt="${$(a||"")}" loading="lazy" />
        <p class="gallery-descr">
          Likes: <span class="descr-span">${e}</span>
          &nbsp; Views: <span class="descr-span">${s}</span>
          &nbsp; Comments: <span class="descr-span">${o}</span>
          &nbsp; Downloads: <span class="descr-span">${p}</span>
        </p>
      </a>
    </li>
  `).join("")}function L(t=[],{replace:r=!0}={}){const n=S(t);r?u.innerHTML=n:u.insertAdjacentHTML("beforeend",n),b.refresh()}function q(){u.innerHTML=""}function w(){c.style.display="flex",c.innerHTML='<p style="margin:24px 0 0; color:#6b7280">Loading images, please wait…</p>'}function P(){c.style.display="none",c.innerHTML=""}function $(t){return String(t).replace(/[&<>"']/g,r=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[r])}const i={form:document.querySelector(".form"),input:document.querySelector('.form input[name="search-text"]'),gallery:document.querySelector(".gallery"),searchBtn:document.querySelector(".search-btn")};i.form.addEventListener("submit",T);function T(t){t.preventDefault();const r=i.input.value.trim();if(!r){l("The search field can't be empty! Please, enter your request!");return}if(r.length>100){l("Search query must be 100 characters or less.");return}q(),w(),i.searchBtn.disabled=!0,h(r,{page:1,perPage:20,lang:"en"}).then(({hits:n})=>{if(!Array.isArray(n)||n.length===0){l("Sorry, there are no images matching your search query. Please, try again!");return}L(n,{replace:!0}),i.form.reset()}).catch(()=>{l("Something went wrong. Please, try again later.")}).finally(()=>{P(),i.searchBtn.disabled=!1})}function l(t){d.show({class:"error-svg",position:"topRight",icon:"error-svg",message:t,maxWidth:"432",messageColor:"#fff",messageSize:"16px",backgroundColor:"#EF4040",close:!1,closeOnClick:!0})}
//# sourceMappingURL=commonHelpers.js.map
